version: "3.9" 

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: fitforge-postgres-db
    environment:
      POSTGRES_USER: fitforge
      POSTGRES_PASSWORD: fitforgepassword
      POSTGRES_DB: fitforgedb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitforge -d fitforgedb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  db-seeder:
    build:
      context: .
    depends_on:
      postgres-db:
        condition: service_healthy
    command: python seed_db.py

  agent-api:
    container_name: fitforge-agent-api
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      db-seeder:
        condition: service_completed_successfully
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DATABASE_URL: postgresql://fitforge:fitforgepassword@postgres-db:5432/fitforgedb

volumes:
  postgres-data:
